# Site settings
title: 橋本 龍のホームページ
description: 橋本 龍のホームページ
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
user:
  fullname: 
    ja: 橋本 龍
    en: Ryo Hashimoto
  occupation: System Engineer
  email: hashimotoryoh@gmail.com
  twitter_username: hashimotoryoh
  facebook_username: ryoh.hashimoto
  instagram_username: hashimotoryoh
  qiita_username: hashimotoryoh
  note_username: hashimotoryoh

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
