name: Deploy to production env

on:
  release:
    types: [ released ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18.8.0'

      - name: Install node modules
        run: npm install

      - name: Build Production
        run: npm run deploy
