name: Deploy to production env

on:
  release:
    types: [ released ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18.8.0'

      - name: Set version
        run: echo "VITE_APP_VERSION=${GITHUB_REF#refs/*/}"

      - name: Install node modules
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
